export const FAMOUS_HORSE_NAMES = [
  'Bold Pilot',
  'Yavuzhan',
  'Ribella',
  'Karayel',
  'Grand Ekinoks',
  'Trapper',
  'Hafız',
  'Toraman',
  'Gold Guard',
  'Nurtay',
  'Turbo',
  'Seren 1',
  'Tunca',
  'Volga 2',
  'Minimo',
  'Yavuz Star',
  'Ayabakan',
  'Özgünhan',
  'Yelhan',
  'Timurhan',
  'Mirhat',
  'Tansel',
  'Halid',
  'Bozdağ',
  "Tamer'in Oğlu",
  'Johny Guitar',
  'Ramadan',
  'Velociraptor',
  'Medya',
  'Sunday',
  'Surprise',
  'Blow Up',
  'Mandrake',
  'Beretta',
  'Win River Win',
  'Bartrobel',
  'Kaşemumkara',
  'Dragon',
  'Damista',
  'Hücum',
  'Ribella',
  'Keremhan',
  'Rüzgarınkızı',
  'İslambol',
  'Abbas Cihangir',
  'Tünkut',
  'Kafkaslı',
  'Cihangir Harmony',
]
